<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="Brand.aspx.cs" Inherits="StayBeautifulSMS.Brand" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="basicForm-wrapper">
        <div>
            <h2><asp:Label ID="Label4" class="headings" runat="server" Text="Brand"></asp:Label> </h2>
        </div>
        <br />
        <br />
        <div>
            <%--<asp:Label runat="server" class="labels" ID="Label1" Font-Bold="True" Text="Brand Name"></asp:Label>--%>
            <br />
            <asp:TextBox ID="txtBrandName" Height="25px" runat="server" Width="300px" class="textFields" placeholder="Brand Name"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtBrandName" ErrorMessage="Field must not be empty!" ForeColor="Red" ValidationGroup="BrandGroup"></asp:RequiredFieldValidator>
        </div>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="txtBrandName" ErrorMessage="Takes string value only!" ForeColor="Red" ValidationGroup="BrandGroup" ValidationExpression="^[a-zA-Z ]+$"></asp:RegularExpressionValidator>
        <br />
        <div>
            <asp:Button class="submit-button" ID="insertBtn" runat="server" Text="Insert" OnClick="insertBtn_Click"  ValidationGroup="BrandGroup"  />
        </div>
        <br />
        <br />
        <br />
         <div>
             <asp:GridView ID="brandGridView" DataKeyNames="BRAND_ID" runat="server" OnRowDataBound="brandGridView_RowDataBound" OnRowEditing="brandGridView_RowEditing" OnRowUpdating="brandGridView_RowUpdating" OnRowCancelingEdit="brandGridView_RowCancelingEdit" OnRowDeleting="brandGridView_RowDeleting"  AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" Height="369px" HorizontalAlign="Justify" PageSize="15" Width="1200px" GridLines="Horizontal" BorderColor="#CCCCCC" BorderStyle="None" CellPadding="60" CellSpacing="35">

             </asp:GridView>
        </div>
    </div>
</asp:Content>