<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="ItemHistory.aspx.cs" Inherits="StayBeautifulSMS.ItemHistory" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="basicForm-wrapper">
        <div>
            <h2><asp:Label ID="Label4" class="headings" runat="server" Text="Item History"></asp:Label> </h2>
        </div> <br />
    <%--    <div>
        <asp:DropDownList ID="itemsddl" runat="server" DataSourceID="SqlDataSource1" DataTextField="item_name" DataValueField="item_id"></asp:DropDownList>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Provider=SQLNCLI11;Data Source=DESKTOP-TKS66R0;Integrated Security=SSPI;Initial Catalog=&quot;App Dev CW2&quot;" ProviderName="System.Data.OleDb" SelectCommand="SELECT [item_name], [item_id] FROM [Items]"></asp:SqlDataSource>
    </div>--%>
<%--    <div>
        <asp:Button ID="searchBtn" runat="server" Text="SEARCH" onClick="searchBtn_Click"/>
    </div>--%>
    <br />
    <br />
    <div>
        <asp:GridView ID="itemHistoryGridView" runat="server" DataKeyNames="Item_id" AutoGenerateDeleteButton="true" OnRowDeleting="itemHistoryGridView_RowDeleting" Height="369px" HorizontalAlign="Justify" PageSize="15" Width="1200px" GridLines="Horizontal" BorderColor="#CCCCCC" BorderStyle="None" CellPadding="60" CellSpacing="35"></asp:GridView>
    </div> 
    </div>
</asp:Content>
