<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="UnsoldItems.aspx.cs" Inherits="StayBeautifulSMS.Unsold_Items" %>


<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="basicForm-wrapper">
        <div>
            <h2>
                <asp:Label ID="Label4" class="headings" runat="server" Text="Unsold Items"></asp:Label>
            </h2>
        </div>
        <br />
        <div>
            <% if (User.Identity.Name == "admin"){%>
            <asp:GridView ID="unsoldItemsGrid1" OnRowDataBound="unsoldItemsGrid1_RowDataBound" OnRowDeleting="unsoldItemsGrid1_RowDeleting" AutoGenerateDeleteButton="true" runat="server" DataKeyNames="Item_ID" Height="369px" HorizontalAlign="Justify" PageSize="15" Width="1200px" GridLines="Horizontal" BorderColor="#CCCCCC" BorderStyle="None" CellPadding="60" CellSpacing="35"></asp:GridView>
    
            <% }else{%>
            <asp:GridView ID="unsoldItemsGrid" runat="server" DataKeyNames="Item_ID" Height="369px" HorizontalAlign="Justify" PageSize="15" Width="1200px" GridLines="Horizontal" BorderColor="#CCCCCC" BorderStyle="None" CellPadding="60" CellSpacing="35"></asp:GridView>
            <%} %>
        </div>
    </div>
</asp:Content>
